# Generated by Django 5.2.4 on 2025-07-15 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_date_joined_customuser_otp_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='verified_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
