# Generated by Django 5.2.4 on 2025-07-15 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_register_city_customuser_register_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='register_city',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='register_country',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='register_isp',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='register_region',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='verified_city',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='verified_country',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='verified_isp',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='verified_region',
        ),
    ]
