# Generated by Django 5.2.4 on 2025-07-16 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_customuser_phone_number_customuser_register_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='phone_number',
        ),
    ]
